with open('src/app/sleep/components/EnhancedSleepLogger.tsx', 'r', encoding='utf-8') as f:
    text = f.read()

text = text.replace("import { Plus, Moon, Activity, Heart, Frown, Smile, Zap } from 'lucide-react';", "import { Plus, Moon, Activity, Heart, Frown, Smile, Zap } from 'lucide-react';\nimport { useLanguage } from '@/contexts/LanguageContext';")
text = text.replace("export default function EnhancedSleepLogger({ onLogSaved }: EnhancedSleepLoggerProps) {", "export default function EnhancedSleepLogger({ onLogSaved }: EnhancedSleepLoggerProps) {\n    const { t } = useLanguage();")

text = text.replace("> Advanced Sleep Log<", "> {t('sleep.logger.title')}<")
text = text.replace(">Bedtime<", ">{t('sleep.logger.bedtime')}<")
text = text.replace(">Wake time<", ">{t('sleep.logger.waketime')}<")
text = text.replace(">Sleep Duration (hrs)<", ">{t('sleep.logger.duration')}<")
text = text.replace(">Quality<", ">{t('sleep.logger.quality')}<")
text = text.replace(">Excellent<", ">{t('sleep.logger.qualityExcellent')}<")
text = text.replace(">Good<", ">{t('sleep.logger.qualityGood')}<")
text = text.replace(">Fair<", ">{t('sleep.logger.qualityFair')}<")
text = text.replace(">Poor<", ">{t('sleep.logger.qualityPoor')}<")
text = text.replace(">Waking Mood<", ">{t('sleep.logger.wakingMood')}<")
text = text.replace(">Great<", ">{t('sleep.logger.moodGreat')}<")
text = text.replace(">Okay<", ">{t('sleep.logger.moodOkay')}<")
text = text.replace(">Groggy<", ">{t('sleep.logger.moodGroggy')}<")
text = text.replace(">Energy<", ">{t('sleep.logger.energy')}<")
text = text.replace(">High<", ">{t('sleep.logger.energyHigh')}<")
text = text.replace(">Medium<", ">{t('sleep.logger.energyMedium')}<")
text = text.replace(">Low<", ">{t('sleep.logger.energyLow')}<")
text = text.replace(">Stress<", ">{t('sleep.logger.stress')}<")
text = text.replace(">Moderate<", ">{t('sleep.logger.stressModerate')}<")
text = text.replace(">Notes & Thoughts<", ">{t('sleep.logger.notes')}<")
text = text.replace("placeholder=\"How did you sleep?\"", "placeholder={t('sleep.logger.notesPlaceholder')}")
text = text.replace(">Dreams (Optional)<", ">{t('sleep.logger.dreams')}<")
text = text.replace("placeholder=\"Any vivid dreams?\"", "placeholder={t('sleep.logger.dreamsPlaceholder')}")
text = text.replace(">Tags (comma separated)<", ">{t('sleep.logger.tags')}<")
text = text.replace("placeholder=\"e.g. late meal, hot room\"", "placeholder={t('sleep.logger.tagsPlaceholder')}")
text = text.replace("> Save Sleep Entry<", "> {t('sleep.logger.save')}<")

with open('src/app/sleep/components/EnhancedSleepLogger.tsx', 'w', encoding='utf-8') as f:
    f.write(text)
