'use client';
import React from 'react';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';

export default function DisclaimerPage() {
    const { t } = useLanguage();
    
    return (
        <div className="min-h-screen bg-background text-on-surface p-4 sm:p-5 md:p-12 font-sans">
            <div className="max-w-3xl mx-auto bg-surface-container rounded-2xl shadow-sm border border-surface-variant/30 p-8">
                <Link href="/" className="inline-flex items-center gap-2 text-on-surface-variant hover:text-on-surface transition-colors mb-8 font-medium">
                    <ArrowLeft size={18} /> Back
                </Link>
                
                <h1 className="text-3xl font-black text-on-surface mb-2">Medical & Financial Disclaimer</h1>
                <p className="text-sm text-on-surface-variant mb-8">Last Updated: August 2026 (v1.0)</p>

                <div className="space-y-4 text-on-surface leading-relaxed">
                    <section>
                        <h2 className="text-xl font-bold mb-3">1. Medical Disclaimer</h2>
                        <p className="mb-3"><strong>Not Medical Advice:</strong> Workout OS is designed for informational and self-tracking purposes only. The application, including its AI Copilot features, is not intended to be a substitute for professional medical advice, diagnosis, or treatment.</p>
                        <p><strong>Consult a Professional:</strong> Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read on Workout OS.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3">2. Financial Disclaimer</h2>
                        <p><strong>Not Financial Advice:</strong> The Budget Tracker and related financial features within Workout OS are provided for informational and organizational purposes only. We are not registered financial advisors. You should not rely on Workout OS to make significant financial, investment, or tax decisions. Always consult with a licensed financial professional before making financial commitments.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3">3. AI Limitations</h2>
                        <p>The insights and recommendations generated by the AI Copilot are computationally derived and may contain errors, hallucinations, or inaccuracies. You should always verify AI-generated advice—especially regarding diet, exercise routines, or finances—before acting upon it.</p>
                    </section>
                </div>
            </div>
        </div>
    );
}
